namespace AuthenticationSystemAPI.Models;

/*
 * ===================================================================
 * USER MODEL - Entity that represents a user in the database
 * ===================================================================
 * 
 * Clean Architecture - This is the "Entity" layer:
 * - Contains business rules and data
 * - No dependencies on external frameworks
 * - Used by the Data layer for database operations
 * 
 * Key Properties:
 * - Id: Primary key (auto-generated by SQL Server)
 * - Username: Unique identifier for login
 * - Email: Unique contact information
 * - PasswordHash: Stores BCrypt hashed password (NEVER store plain text!)
 * - Role: Authorization level (User, Admin, etc.)
 * - CreatedAt: Timestamp for audit purposes
 */
public class User
{
    // Primary Key - Entity Framework will auto-generate this
    public int Id { get; set; }

    // Username must be unique and not null
    // Max 100 characters to prevent database overflow
    public string Username { get; set; } = string.Empty;

    // Email must be unique and not null
    // Used for account verification and password reset
    public string Email { get; set; } = string.Empty;

    // IMPORTANT: Never store plain-text passwords!
    // We store BCrypt hash which is:
    // - One-way: Cannot be decrypted back to original
    // - Salted: Each hash includes a random salt
    // - Slow: Designed to resist brute-force attacks
    public string PasswordHash { get; set; } = string.Empty;

    // Role-based authorization: Determines what user can access
    // Default is "User" - can be "Admin", "Moderator", etc.
    public string Role { get; set; } = "User";

    // Track when account was created - useful for auditing
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

